name: Deploy by Docker pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t gcp_deploy .

      - name: Push image to Docker Hub with tag lts
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gcp_deploy:lts

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the image that was pushed to DockerHub
            docker pull ${{ secrets.DOCKER_USERNAME }}/gcp_deploy:lts

            docker stop gcp-deploy-container
            docker rm gcp-deploy-container

            # Run a new container with the pulled image
            docker run --name gcp-deploy-container ${{ secrets.DOCKER_USERNAME }}/gcp_deploy:lts
