name: Deploy by docker pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull image mà được push lên DockerHub bên trên
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/gcp_deploy:${{ github.sha }}

            # Dừng và gỡ bỏ container hiện tại (nếu có)
            docker stop gcp-deploy-container
            docker rm gcp-deploy-container

            # Chạy container mới với image đã pull về bên trên
            docker run --name gcp-deploy-container gcp_deploy
